name: Build and Lint

on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
        env:
          CI: true

      - name: Create NPM package
        run: npm pack

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tgz'
